export const canonicalUnits: Record<string, string> = {
  creatinine: 'mg/dL',
  sdma: 'μg/dL',
  bun: 'mg/dL',
  phosphorus: 'mg/dL',
  potassium: 'mmol/L',
  calcium: 'mg/dL',
  sodium: 'mmol/L',
  chloride: 'mmol/L',
  albumin: 'g/dL',
  total_protein: 'g/dL',
  urine_specific_gravity: '',
  upc_ratio: '',
  urine_ph: '',
  hematocrit: '%',
  hemoglobin: 'g/dL',
  wbc: '10^3/μL',
  platelets: '10^3/μL',
  alt: 'U/L',
  ast: 'U/L',
  alkp: 'U/L',
  glucose: 'mg/dL',
  t4: 'μg/dL',
};
