export const canonicalUnits: Record<string, string> = {
  // Chemistry / kidney
  creatinine:             'mg/dL',
  sdma:                   'μg/dL',
  bun:                    'mg/dL',
  phosphorus:             'mg/dL',
  potassium:              'mmol/L',
  calcium:                'mg/dL',
  sodium:                 'mmol/L',
  chloride:               'mmol/L',
  albumin:                'g/dL',
  total_protein:          'g/dL',
  // Urine
  urine_specific_gravity: '',
  upc_ratio:              '',
  urine_ph:               '',
  // CBC – red cell
  hematocrit:             '%',
  hemoglobin:             'g/dL',
  rbc:                    '10⁶/μL',
  mcv:                    'fL',
  mch:                    'pg',
  mchc:                   'g/dL',
  rdw_cv:                 '%',
  rdw_sd:                 'fL',
  // CBC – white cell
  wbc:                    '10³/μL',
  neutrophils:            '10³/μL',
  lymphocytes:            '10³/μL',
  monocytes:              '10³/μL',
  eosinophils:            '10³/μL',
  basophils:              '10³/μL',
  // CBC – platelets
  platelets:              '10³/μL',
  mpv:                    'fL',
  pdw:                    '%',
  pct:                    '%',
  // Liver / endocrine
  alt:                    'U/L',
  ast:                    'U/L',
  alkp:                   'U/L',
  alp:                    'U/L',
  ggt:                    'U/L',
  bilirubin:              'mg/dL',
  glucose:                'mg/dL',
  t4:                     'μg/dL',
  cholesterol:            'mg/dL',
  triglycerides:          'mg/dL',
};
